### ISSUE TITLE
python3.11 not working

### ISSUE THREAD

**Issue by j44k** [JoeJoeTV/AstroTuxLauncher#1]
Can you update to work with python3.11 ? 

python3 AstroTuxLauncher.py install
Traceback (most recent call last):
  File "/home/user/AstroTuxLauncher/AstroTuxLauncher.py", line 113, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1220, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1210, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class '__main__.NotificationConfig'> for field notifications is not allowed: use default_factory
acid@dkek:~/AstroTuxLauncher$

**Comment by JoeJoeTV** [comment]
Thanks for reporting, this issue should be fixed in commit 404829b67e589ff43cf7dbec09e23b67662d94c6.

Can you try if it works for your setup now?

**Comment by j44k** [comment]
Works !! 
Damn that was quick.

**Comment by JoeJoeTV** [comment]
Alright, I'll make a new release with the fix and close this issue.
