### ISSUE TITLE
Issues implementing Launcher with Dockers 

### ISSUE THREAD

**Issue by TophC7** [JoeJoeTV/AstroTuxLauncher#4]
I'm trying to install this server in an alpine docker but when I try installing, I keep getting an error message. The file downloaded and I can access it. I'm not sure why it says it can't find it. I'd troubleshoot further but I'm not great with python. What could be the cause of this?

Error Message:
```
[07:42:23] [Launcher/CRITICAL] Error while installing server on line 591: FileNotFoundError: [Errno 2] No such file or directory: '/opt/mcsmanager/daemon/data/InstanceData/c2f50c3040e440ab811eff866e6e66f1/libs/depotdownloader'
[07:42:23] [Launcher/ERROR] Traceback (most recent call last):
  File "/opt/mcsmanager/daemon/data/InstanceData/c2f50c3040e440ab811eff866e6e66f1/AstroTuxLauncher.py", line 591, in <module>
    launcher.update_server()
  File "/opt/mcsmanager/daemon/data/InstanceData/c2f50c3040e440ab811eff866e6e66f1/AstroTuxLauncher.py", line 390, in update_server
    success = steam.update_app(exec_path=self.depotdl_path, app="728470", os="windows", directory=self.config.AstroServerPath)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/mcsmanager/daemon/data/InstanceData/c2f50c3040e440ab811eff866e6e66f1/utils/steam.py", line 135, in update_app
    proc_res = run_proc_with_logging(cmd_args, "DepotDL", level=logging.DEBUG, alive_bar=bar)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/mcsmanager/daemon/data/InstanceData/c2f50c3040e440ab811eff866e6e66f1/utils/interface.py", line 954, in run_proc_with_logging
    process = subprocess.Popen(args, stderr=subprocess.PIPE, stdout=subprocess.PIPE, bufsize=1, close_fds=True, text=True, **popen_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/mcsmanager/daemon/data/InstanceData/c2f50c3040e440ab811eff866e6e66f1/libs/depotdownloader'
```

**Comment by JoeJoeTV** [comment]
Hmm, AstroTuxLauncher can't find the depotdownloader binary, which normally, it will download itself.
Did you give AstroTuxLauncher any arguments when executing it?
Also, please attach the last log file that AstroTuxLauncher should have generated in the "logs/" folder.

**Comment by TophC7** [comment]
I did not. I simply ran `python3 AstroTuxLauncher.py install`

Here's the full log
```
[18:28:47] [Launcher/INFO] Working directory: /opt/mcsmanager/daemon/data/InstanceData/04e9bf5018764153b3d1b43012c9e196
[18:28:47] [DedicatedServer/INFO] Overwriting PublicIP field in Dedicated Server config...
[18:28:47] [Net/INFO] Getting IP from remote service
[18:28:47] [DedicatedServer/INFO] NOTICE: Encryption is disabled. All players that want to join the Dedicated Server have to disable encryption on their clients too
[18:28:47] [Launcher/INFO] Installing Astroneer Dedicated Server...
[18:28:47] [Launcher/INFO] DepotDownloader not found, downloading...
[18:28:48] [Steam/INFO] Finished downloading DepotDownloader in 1.23 seconds
[18:28:48] [Launcher/INFO] Updating Astroneer Dedicated Server app from Steam...
[18:28:48] [Launcher/CRITICAL] Error while installing server on line 591: FileNotFoundError: [Errno 2] No such file or directory: '/opt/mcsmanager/daemon/data/InstanceData/04e9bf5018764153b3d1b43012c9e196/libs/depotdownloader'
[18:28:48] [Launcher/ERROR] Traceback (most recent call last):
  File "/opt/mcsmanager/daemon/data/InstanceData/04e9bf5018764153b3d1b43012c9e196/AstroTuxLauncher.py", line 591, in <module>
    launcher.update_server()
  File "/opt/mcsmanager/daemon/data/InstanceData/04e9bf5018764153b3d1b43012c9e196/AstroTuxLauncher.py", line 390, in update_server
    success = steam.update_app(exec_path=self.depotdl_path, app="728470", os="windows", directory=self.config.AstroServerPath)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/mcsmanager/daemon/data/InstanceData/04e9bf5018764153b3d1b43012c9e196/utils/steam.py", line 135, in update_app
    proc_res = run_proc_with_logging(cmd_args, "DepotDL", level=logging.DEBUG, alive_bar=bar)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/mcsmanager/daemon/data/InstanceData/04e9bf5018764153b3d1b43012c9e196/utils/interface.py", line 954, in run_proc_with_logging
    process = subprocess.Popen(args, stderr=subprocess.PIPE, stdout=subprocess.PIPE, bufsize=1, close_fds=True, text=True, **popen_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/mcsmanager/daemon/data/InstanceData/04e9bf5018764153b3d1b43012c9e196/libs/depotdownloader'
````

**Comment by TophC7** [comment]
Actually, I got it to work in a Debian based docker with no special set up. Alpine is just weird.

But now I'm having an issue where I can't connect to the host, it's always unreachable. My port is open, and I have encryption disabled on client and server, is there anything else that can cause issues on the connection?

**Comment by JoeJoeTV** [comment]
Ok, strange, it seems like the deoptdownloader file wasn't downloaded correctly in alpine.

For the connection issues: What does https://servercheck.spycibot.com tell you? If the server is both registered and reachable (AstroTuxLauncher should also tell you about potential issues in this area), then the problem could be related to NAT.
Are you connecting to the server from the same network? Firstly, you can't use the local IP to connect, you always need to enter the public IP in the client.
Secondly, if you're already using the public IP, you probably have an issue with NAT loopback. Check that this is enabled in your router.
With playit.gg, this should normalls work.
Can you tell me, if AstroTuxLauncher outputs any warnings when you try it using playit.gg?

**Comment by TophC7** [comment]
Server is registered but unreachable in the check. And now I'm using an external IP never localhost or LAN.
The current log is not very helpful really
```
[22:58:11] [Launcher/INFO] Working directory: /astroneer
[22:58:11] [DedicatedServer/INFO] NOTICE: Encryption is disabled. All players that want to join the Dedicated Server have to disable encryption on their clients too
[22:58:11] [Launcher/INFO] No update available, the Astroneer Dedicated Server is on the newest version
[22:58:11] [Launcher/INFO] Checking Network Configuration...
[22:58:27] [Launcher/WARNING] The Server is completely unreachable
[22:58:27] [Launcher/WARNING] Make sure the Server Port (16352) is forwarded for UDP traffic and check firewall settings
[22:58:37] [Launcher/INFO] RCON network configuration looks good
[22:58:37] [DedicatedServer/INFO] Preparing to start the Dedicated Server...
[22:58:37] [DedicatedServer/INFO] Started Dedicated Server process (v1.29.61.0). Waiting for registration...
[22:58:54] [DedicatedServer/INFO] Dedicated Server ready! Took 16.38 seconds to register
[22:58:54] [Notify/INFO] Server started!
[22:58:54] [Launcher/INFO] Enter 'help' to get help about command usage
```
I also noticed my port is not really being used? Or maybe in missing something but with ss -antpl I dont see the pot 16352 anywhere.

Here's my setup docker setup

Dockerfile
``` Dockerfile
FROM ubuntu:24.04 as astroneer
USER root
WORKDIR /astroneer
ENV PYTHONUNBUFFERED=1
RUN apt-get update && apt-get install -y git python3 python3-pip wine && rm -rf /var/lib/apt/lists/* && ln -sf python3 /usr/bin/python
RUN pip3 install --no-cache --upgrade --break-system-packages pip setuptools
RUN git clone https://github.com/JoeJoeTV/AstroTuxLauncher ./
RUN pip install -r requirements.txt --break-system-packages && python3 AstroTuxLauncher.py install
ENTRYPOINT [ "python3", "AstroTuxLauncher.py", "start" ]

FROM ubuntu:24.04 as playit
RUN apt-get update && apt-get install -y curl gnupg
RUN curl -SsL https://playit-cloud.github.io/ppa/key.gpg | apt-key add - && curl -SsL -o /etc/apt/sources.list.d/playit-cloud.list https://playit-cloud.github.io/ppa/playit-cloud.list
RUN apt-get update && apt-get install playit -y && rm -rf /var/lib/apt/lists/*
ENTRYPOINT [ "playit" ]
```
compose.yaml
``` yaml
version: "3.9"
services:
    astroneer:
        tty: true
        stdin_open: true
        container_name: astroneer
        build:
            context: .
            dockerfile: Dockerfile
            target: astroneer
        ports:
            - 16352:16352/udp
        volumes:
            - ./Saved:/astroneer/AstroneerServer/Astro/Saved
            - ./logs:/astroneer/logs
            - ./launcher.toml:/astroneer/launcher.toml
    playit:
        build:
            context: .
            dockerfile: Dockerfile
            target: playit
        container_name: playit
        restart: unless-stopped
        volumes:
            - ./playit:/etc/playit
```

**Comment by JoeJoeTV** [comment]
Ok, the server is unreachable, so no connection could be made to the astroneer server from the internet.
That means that probably, something with your playit.gg setup is wrong.
Does the IP and port given to the Astroneer Server in it's config (you can get that normally by executing the `info` command after AstroTuxLauncher has started) match the IP and port given by playit.gg?

Also, you mentioned the `ss` command. This will not work, as the Astroneer Server uses UDP, while AFAIK `ss` is used to display TCP connections. Try using `netstat -tunlp` for all listening ports.

**Comment by JoeJoeTV** [comment]
Also, how did you create the tunnel on playit.gg, did you use a shared IP with UDP and a matching local to public port?

**Comment by TophC7** [comment]
Okay its working now!!
It was indeed the IP with playit.gg, found the Ip for the astroneer container and gave that to playit.gg and now it works! Now im wandering why it wouldn't work with my static ip but problem for another day haha

Thanks again for the help and the super useful linux server.

**Comment by JoeJoeTV** [comment]
No problem, the static IP issue could be a NAT loopback problem, if you just couldn't connect from the local network.
Otherwise, maybe the port-forwarding is somehow configured wrong or your firewall is blocking incoming connections to that port.

Otherwise, this issue is resolved, so I can close it, correct?

**Comment by TophC7** [comment]
yes, resolved the issue. Thanks again
